/-
Copyright (c) 2026 Nelson Spence. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nelson Spence
-/
import Mathlib.Combinatorics.SimpleGraph.Metric
import Mathlib.Combinatorics.SimpleGraph.Finite
import Mathlib.Analysis.SpecialFunctions.Log.Basic

set_option relaxedAutoImplicit false
set_option autoImplicit false

/-!
# Log-Ratio Dimension for Graph Families

Defines `HasLogRatioDimension`, a predicate asserting that the ratio
`log |V(G_g)| / log (dist(s_g, t_g))` converges to `d` as `g → ∞`
for a sequence of finite simple graphs with distinguished vertex pairs.

For self-similar graph families (such as the (u,v)-flower), this limit
coincides with the box-counting fractal dimension. In general it is a
growth exponent — a formal equivalence to box-covering dimension for
specific families would be a separate theorem.

This definition was initially generated by Aristotle (Harmonic) under
the name `HasBoxCountingDimension` and renamed to reflect what it
actually defines. See `docs/aristotle/artifacts/HasBoxCountingDimension.lean`
for the original.

## Main definitions

- `HasLogRatioDimension` — the log-ratio limit equals `d`

## References

- [Rozenfeld2007] §2, dimension as log-ratio limit for flower graphs.

## Tags

graph dimension, log-ratio, growth exponent, box-counting dimension
-/

open Real Filter

/-- A sequence of finite simple graphs `G_g` with distinguished vertices
`s_g`, `t_g` has **log-ratio dimension** `d` if
`log |V(G_g)| / log (dist(s_g, t_g))` tends to `d` as `g → ∞`.

For self-similar families this coincides with the box-counting dimension.
In general it is a growth exponent; equivalence to box-covering for
specific families requires a separate proof. -/
def HasLogRatioDimension
    {V : ℕ → Type*} [∀ g, Fintype (V g)]
    (G : (g : ℕ) → SimpleGraph (V g))
    (s t : (g : ℕ) → V g)
    (d : ℝ) : Prop :=
  Tendsto
    (fun g ↦ log (Fintype.card (V g) : ℝ) / log ((G g).dist (s g) (t g) : ℝ))
    atTop (nhds d)
