/-
Copyright (c) 2026 Nelson Spence. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nelson Spence
-/
import Mathlib.Combinatorics.SimpleGraph.Metric
import Mathlib.Combinatorics.SimpleGraph.Finite
import Mathlib.Analysis.SpecialFunctions.Log.Basic

/-!
# Log-Ratio Dimension for Graph Families

Defines `HasLogRatioDimension`, a predicate asserting that the ratio
`log |V(G_g)| / log (dist(s_g, t_g))` converges to `d` as `g → ∞`
for a sequence of finite simple graphs with distinguished vertex pairs.

The limit depends on the chosen pair `s_g`, `t_g`: the same graphs with
differently spaced pairs can have different exponents. It is not box-counting
dimension in general. `HasBoxDimension` in `FlowerBoxDimension.lean` is the
pair-independent notion; for the flowers both hold with the same value
(`flowerGraph_hasLogRatioDimension`, `flowerGraph_hasBoxDimension`).

This definition was first generated by Aristotle (Harmonic) under the name
`HasBoxCountingDimension` and renamed to reflect what it defines.

## Main definitions

- `HasLogRatioDimension` — the log-ratio limit equals `d`

## Main statements

None: this file only defines the predicate. `FlowerGraphDimension` proves it for the flowers.

## Implementation notes

`G g` has `Fintype.card (V g)` vertices, and `dist` is `SimpleGraph.dist`, which is `0` for
unreachable pairs; the flower graphs are connected, so this junk value does not arise there.

## References

- [Rozenfeld2007] §2, dimension as log-ratio limit for flower graphs.

## Tags

graph dimension, log-ratio, growth exponent, box-counting dimension
-/

open Real Filter

/-- A sequence of finite simple graphs `G_g` with distinguished vertices
`s_g`, `t_g` has **log-ratio dimension** `d` if
`log |V(G_g)| / log (dist(s_g, t_g))` tends to `d` as `g → ∞`.

This is a pair-dependent growth exponent. Identifying it with box-counting
dimension requires additional hypotheses and a separate theorem. -/
def HasLogRatioDimension
    {V : ℕ → Type*} [∀ g, Fintype (V g)]
    (G : (g : ℕ) → SimpleGraph (V g))
    (s t : (g : ℕ) → V g)
    (d : ℝ) : Prop :=
  Tendsto
    (fun g ↦ log (Fintype.card (V g) : ℝ) / log ((G g).dist (s g) (t g) : ℝ))
    atTop (nhds d)
